[package]
name = "spade"
version = "1.2.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
description="Spatial datastructures like r-trees and delaunay triangulations for rust."
documentation = "https://docs.rs/spade/"
repository = "https://github.com/Stoeoef/spade"
readme = "README.md"
keywords = ["delaunay", "triangulation", "rtree", "geometry", "interpolation"]
license = "MIT/Apache-2.0"

[dependencies]
cgmath = ">=0.10.0, <=0.15.0"
nalgebra = ">=0.11.0, <=0.13.*"
num = "0.1.*"
clamp = "0.1.*"
smallvec = "0.4.*"

[dev-dependencies]
rand = "0.3.*"
time = "0.1.*"
approx = "0.1.*"

[profile.bench]
opt-level = 3
debug-assertions = false

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
